services:
  db:
    image: postgres:16
    container_name: expense-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:
